### ISSUE TITLE
main.css issue

### ISSUE THREAD

**Issue by Cili23** [Cili23/dinosaur-designs#1]
@hellachella
@carolsinc

I am unsure what I did wrong on line seven?

<img width="1121" alt="Screen Shot 2021-03-12 at 13 49 08 PM" src="https://user-images.githubusercontent.com/77252057/110984985-d4b5f080-8339-11eb-8f59-f14241891e17.png">

**Comment by carolsinc** [comment]
your line-height isn't closed

**Comment by Cili23** [comment]
Thank you, However that did not fix my line 7 issue according to Markbot

**Comment by hellachella** [comment]
` <link href="css/main.css" rel="stylesheet">`
